#include <iostream>
#include <ctime>
using namespace std;
class start{
public:
start(){ //constructor to welcome player
for(int j=0;j<2;j++){
for(int i=0;i<40;i++){
cout<<" * ";
}
cout<<endl;
}
for(int i=0;i<15;i++){
cout<<" * ";
}
cout<<" WELCOME TO CASINO ARCADE GAME ";
for(int i=0;i<15;i++){
cout<<" * ";
}
cout<<endl;
for(int j=0;j<2;j++){
for(int i=0;i<40;i++){
cout<<" * ";
}
cout<<endl;
}
cout<<endl<<endl;
}
~start(){} //Destructor
void rules();
virtual userinfo()=0;
};
void start :: rules(){ //function to specify rules of the game
for(int i=0;i<60;i++){
cout<<" # ";
}
cout<<endl<<endl;
cout<<" Following are the rules to play the game: "<<endl<<endl;
cout<<" 1. Start by inputting the players information required to proceed further. "<<endl<<endl;
cout<<" 2. Choose a number between 1 to 10 and any CAPITAL digit alphabet."<<endl<<endl;

cout<<" 3. If only the number inputted by user matches computer number,player will get 2 times more money than they bet,5 times more money if alphabet matches and 10 times more if both matches."<<endl<<endl;
cout<<" 4. But if lost, the amount of money bet would be withdrawn from the players account."<<endl<<endl;
cout<<" 5. A person can continue to play unless the amount of money present in their bank account surpasses the minimum amount required to play the game which is 100 rupees."<<endl<<endl;
for(int i=0;i<60;i++){
cout<<" # ";
}
cout<<endl;
}
class calculation{
protected:
char b_character;
int n;
int m_avail,minimum=100,m_bet,b_number;
public:
int generate_number(){ //function to generate random number by computer
srand(time(NULL));
int m=rand()%10+1;
return m;
}
char generate_character(){ //function to generate random number by computer
srand(time(NULL));
char m=rand()%26+65;
return m;
}
int number_add(){ //function to add money if player wins
m_avail=m_avail+(m_bet*2);
return m_avail;
}
int alphabet_add(){ //function to add money if player wins
m_avail=m_avail+(m_bet*5);
return m_avail;
}
int jackpot_add(){ //function to add money if player wins
m_avail=m_avail+(m_bet*10);
return m_avail;
}
int balance_sub(){ //function to subtract money if player loses
m_avail=m_avail-m_bet;
return m_avail;
}
void check_both(){ //function to check number by player and computer
int u=generate_number();

char o=generate_character();
cout<<"The number you bet on: "<<b_number<<endl;
cout<<"The character you bet on: "<<b_character<<endl;
for(int i=0;i<30;i++){
cout<<"- ";
}
cout<<endl;
cout<<"The number generated by computer is: "<<u<<endl;
cout<<"The character generated by computer is: "<<o<<endl<<endl;
if(u==b_number && o!= b_character){
cout<<" CONGRATULATIONS !!!!!!"<<endl;
cout<<" The number you bet on was CORRECT. ";
cout<<endl<<endl;
int t=number_add();
cout<<"Available balance in your account now is: "<<t<<endl<<endl;
}
else if(o==b_character && u!=b_number){
cout<<" CONGRATULATIONS !!!!!!"<<endl;
cout<<" The alphabet you bet on was CORRECT. ";
cout<<endl<<endl;
int t=alphabet_add();
cout<<"Available balance in your account now is: "<<t<<endl<<endl;
}
else if(o==b_character && u==b_number){
cout<<" JACKPOTTTT !!!!!!"<<endl;
cout<<" The alphabet and number you bet on were BOTHHH CORRECTTTT !!!!!!!!. ";
cout<<endl<<endl;
int t=jackpot_add();
cout<<"Available balance in your account now is: "<<t<<endl<<endl;
}
else{
cout<<" HARD LUCK <3 "<<endl;
cout<<" BOTH you bet on were INCORRECT. ";
cout<<endl<<endl;
int g= balance_sub();
cout<<"Available balance in your account is: "<<g<<endl<<endl;
}
}
};
class main_game : public start,public calculation{
private:
string name;
string num;
public:
int userinfo(){ //function to input details of player

cout<< "Enter SIGN IN details: "<<endl<<endl;
cout<<"Enter your full name: ";
getline(cin,name);
f3:
cout<<"Enter valid mobile number: ";
cin>>num;
if(num.length()>10 || num.length()<10){
cout<<"INVALID phone number "<<endl;
goto f3;
}
cout<<endl;
cout<<" SIGN IN SUCCESSFUL !!! "<<endl<<endl;
cout<<"Enter the amount of money available in bank account: ";
cin>>m_avail;
if(m_avail<minimum){
cout<<"You cannot continue further as there is not enough balance in your account."<<endl;
int m=1;
return m;
}
f1:
cout<<"Enter the amount to bet: ";
cin>>m_bet;
if(m_bet>m_avail){
cout<<"Not enough balance, Please enter valid amount "<<endl;
goto f1;
}
cout<<endl;
f2:
cout<<"Enter the number to bet on between 1 to 10: ";
cin>>b_number;
if(b_number<1 || b_number>10){
cout<<" INVALID INPUT "<<endl;
goto f2;
}
f4:
cout<<"Enter the CAPITAL alphabet to bet on: ";
cin>>b_character;
n=b_character;
if(n<65 || n>90){
cout<<" INVALID INPUT "<<endl;
goto f4;
}
cout<<endl;
}
int check_continue(){ //function to ask if player wants to continue the game
char rep;

cout<<"Do you want to continue the game(Y/N)? : ";
cin>>rep;
cout<<endl;
if(rep=='Y'){
if(m_avail<minimum){
cout<<"You cannot continue further as there is not enough balance in your account."<<endl<<endl;
int m=1;
return m;
}
else{
l1:
cout<<"Enter the amount to bet: ";
cin>>m_bet;
if(m_bet>m_avail){
cout<<"Not enough balance, Please enter valid amount: "<<endl;
goto l1;
}
cout<<endl;
l2:
cout<<"Enter the number to bet on between 1 to 10: ";
cin>>b_number;
if(b_number<1 || b_number>10){
cout<<" INVALID INPUT "<<endl;
goto l2;
}
l4:
cout<<"Enter the CAPITAL alphabet to bet on: ";
cin>>b_character;
n=b_character;
if(n<65 || n>90){
cout<<" INVALID INPUT "<<endl;
goto l4;
}
cout<<endl;
}
}
else{
int g=1;
return g;
}
}
};
int main(){
main_game o;
o.rules();

cout<<endl;
int g=o.userinfo();
if(g==1){
return 0;
}
else{
t1:
o.check_both();
int u=o.check_continue();
if(u==1){
for(int i=0;i<30;i++){
cout<<" ~";
}
cout<<endl;
cout<<" THANK YOU FOR PLAYING THE GAME, HOPE YOU ENJOYED IT<3 "<<endl;
for(int i=0;i<30;i++){
cout<<" ~";
}
cout<<endl<<endl;
return 0;
}
else{
goto t1;
}
}
}
